apiVersion: v1
kind: Pod
metadata:
  name: nova-demo
  labels:
    name: nova-demo
    app: nova-demo
spec:
  containers:
    - name: nova-demo
      image: nova-demo
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 3000
