apiVersion: extensions/v1
kind: ReplicaSet
metadata:
  labels:
    app: nova-demo
  name: nova-demo-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nova-demo
    template:
      metadata:
        labels:
          app: nova-demo
      spec:
        containers:
          - image: nova-demo
            name: nova-demo
            imagePullPolicy: IfNotPresent
