apiVersion: v1
kind: Service
metadata:
  name: nova-demo
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nova-demo
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
