---
# Source: nova-kubernetes-yamls/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nova-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nova-demo
  template:
    metadata:
      labels:
        app: nova-demo
    spec:
      containers:
        - name: nova-demo
          image: nova-demo:v0.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
