---
# Source: nova-kubernetes-yamls/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nova-demo
spec:
  type: NodePort
  selector:
    app: nova-demo
  ports:
    - port: 4000
      targetPort: 80
      nodePort: 30000
